version: "3"
services:
  db:
    image: "postgres"
    container_name: "webrain"
    ports:
      - "5432:5432"
    volumes:
      - ./docker/data:/var/lib/postgresql/webrain
    environment:
      - POSTGRES_USER=webrain
      - POSTGRES_PASSWORD=webrain1!
      - POSTGRES_DB=web



# daemon 실행 : docker-compose up -d
# 로그 확인 : docker logs -f webrain
# psql : docker exec -it webrain -d web -U webrain
# database 생성 : docker exec -it postgres -U webrain -c "create database temp"

# callcarm 유저 생성 > CREATE USER itechs WITH PASSWORD 'dkdlxldptm1!'
# callcrm database 생성 > CREATE DATABASE cardata
# callcrm 유저에게 callcrm 데이터베이스 모든 권한 부여 > GRANT ALL ON DATABASE cardata TO itechs

# temp db 생성 : docker exec -it webrain psql -d webrain -U webrain -c "create database temp"
# cardata db 삭제 : docker exec -it cardata psql -d temp -U itechs -c "drop database cardata"
# cardata db 재생성 : docker exec -it cardata psql -d temp -U itechs -c "create database cardata"
# cardata db 권한부여 : docker exec -it cardata psql -d temp -U itechs -c "GRANT ALL ON DATABASE cardata TO itechs"
